### ISSUE TITLE
Unable to set DisableForeignKeyConstraintWhenMigrating

### ISSUE THREAD

**Issue by zaosoula** [go-goyave/goyave#147]
## Bug report

**Version:** 3.9.1
**Environment:** Mac OS, go1.15.2 darwin/amd64 
**Reproduces:** always

Unable to set DisableForeignKeyConstraintWhenMigrating in gorm.Config

>**panic: constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator**

**Relevant logs:**
```
SELECT count(*) FROM sqlite_master WHERE type = "table" AND tbl_name = "replies" AND (sql LIKE "%CONSTRAINT \"fk_replies_user\" %" OR sql LIKE "%CONSTRAINT fk_replies_user %" OR sql LIKE "%CONSTRAINT `fk_replies_user`%")
panic: constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator

goroutine 1 [running]:
goyave.dev/goyave/v3/database.Migrate()
        /Users/zaosoula/go/pkg/mod/goyave.dev/goyave/v3@v3.9.1/database/database.go:122 +0x11e
goyave.dev/goyave/v3.Start(0x46d3ae8, 0xc000143f68, 0x1)
        /Users/zaosoula/go/pkg/mod/goyave.dev/goyave/v3@v3.9.1/goyave.go:154 +0x11f
main.main()
        /Applications/MAMP/htdocs/projet-forum/api/main.go:24 +0x95
exit status 2
2021/06/22 09:29:47 exit status 1
```

**Database models**
```go
type User struct {
	ID           int32  `gorm:"primary_key;AUTO_INCREMENT;column:id;type:integer;" json:"id" auth:"username"`
	Email        string `gorm:"column:email;type:varchar;" json:"email"`
	DisplayName  string `gorm:"column:displayName;type:varchar;" json:"displayName"`
	UserName     string `gorm:"column:userName;type:varchar;size:30;" json:"userName"`
	Password     string `gorm:"column:password;type:varchar;size:255;" json:"-"`
	LastLoginAt  int    `gorm:"column:lastLoginAt;type:integer;" json:"lastLoginAt"`
	RegisteredAt int    `gorm:"column:registeredAt;type:integer;" json:"registeredAt"`
	RefreshToken string `gorm:"column:refreshToken;type:varchar;size:1000;" json:"-"`
}

type Replies struct {
	ID     int32  `gorm:"primary_key;AUTO_INCREMENT;column:id;type:integer;" json:"id"`
	PostID int    `gorm:"column:postId;type:integer;" json:"postId"`
	Body   string `gorm:"column:body;type:varchar;" json:"body"`
	UserID int    `gorm:"column:userId;type:integer;" json:"userId"`
	User   User

	CreatedAt int `gorm:"column:createdAt;type:integer;" json:"createdAt"`
}
```

### How it occurred

1. Create an association (in this case a User in a Replies)
2. Gorm throw an error asking to set DisableForeignKeyConstraintWhenMigrating to true (which seems not possible with Goyave

**Expected result:**  
Be able to add properties to gorm.Config before the connection occurs

## Additional information

The config is set in [goyave/database/database.go](https://github.com/go-goyave/goyave/blob/master/database/database.go), line 168

**Comment by System-Glitch** [comment]
Hello,

You may want to try using a [connection initializer](https://goyave.dev/guide/basics/database.html#connection-initializers) to set this option:

```go
database.AddInitializer(func(db *gorm.DB) {
    db.Config.DisableForeignKeyConstraintWhenMigrating = true
})
```

Add this before `goyave.Start()` in `main.go`.

I like the ability to set Gorm options from the config though. Thank you very much for your PR, I'll review it when it's ready!

**Comment by zaosoula** [comment]
Hello,

I had not seen the connection initializer 👍 

Also the PR is ready !
