### ISSUE TITLE
HTTP cache implementation as middleware

### ISSUE THREAD

**Issue by darkweak** [go-goyave/goyave#178]
## Proposal

An HTTP cache system would be great in goyave to avoid the execution of unchanged response.
I can implement [Souin](https://github.com/darkweak/souin) as the HTTP cache middleware. With that it will support the CDN validation/invalidation too, set default cache-control header, store in a distributed system using olric or in memory with badger.

It's already available as many plugin/middleware solutions, and is used in the official caddy cache-handler..

### Possible drawbacks

None

## Additional information

I will first add the http cache implementation in the Souin repository and if you want I can implement it directly in the goyave repository.

Cheers ✌️

**Comment by System-Glitch** [comment]
Hello and thank you for your proposal! This looks very interesting. Don't hesitate to ask me if you need any help or guidance.

**Comment by darkweak** [comment]
Merged and available using the `github.com/darkweak/souin/plugins/goyave` dependency. You can find the related documentation here [https://github.com/darkweak/souin/tree/master/plugins/goyave](https://github.com/darkweak/souin/tree/master/plugins/goyave). ✌️
