### ISSUE TITLE
Http Client for goyave

### ISSUE THREAD

**Issue by Tchayo** [go-goyave/goyave#185]
## Support
**Version:** [v4]  
Is there a http client for goyave or do I have to use net/http?

**Comment by System-Glitch** [comment]
Goyave is REST API framework, you can use anything that is using the HTTP protocol to make requests to it.

**Comment by Tchayo** [comment]
I mean from withing goyave controllers. i.e let's say I wanted to fetch some data form https://xxxx.json form my controller, is there any utility for that?

**Comment by System-Glitch** [comment]
Ah I see. No there is nothing built in the framework for that.

**Comment by Tchayo** [comment]
Any suggestions about the package I can use to achieve this?

**Comment by System-Glitch** [comment]
I would use `net/http` but there are probably some viable HTTP client libraries that exist.

**Comment by Tchayo** [comment]
I will use net/http Thanks for the assist.
