### ISSUE TITLE
Validation made for autocomplete

### ISSUE THREAD

**Issue by Wulfheart** [go-goyave/goyave#190]
As far as I currently understand the docs we need to type in strings which is quite unfriendly in an IDE with autocomplete features.

What do you think about providing constants or functions, so 
```go
var (
	StoreRequest = validation.RuleSet{
		"name":  validation.List{"required", "string", "between:3,50"},
	}
)
```
would become
```go
var (
	StoreRequest = validation.RuleSet{
		"name":  validation.List{v.Required(), v.String(), v.Between(3,50)},
	}
)
```

**Comment by System-Glitch** [comment]
Hello @Wulfheart and thank you for your suggestion! You will be happy to hear that I have already implemented this feature for v5. It looks almost exactly like your example. The only difference is that rule sets are now returned by functions that have access to the current request:

```go
func EchoBody(r *goyave.Request) v.RuleSet {
  return v.RuleSet{
    "text": v.List{v.Required(), v.String(), v.Between(3, 5)},
  }
}
```

It is still compatible with composition and has improved field comparison mechanism, among other things.

**Comment by Wulfheart** [comment]
Ah. Thanks for the information. In this case it is already supported.

**Comment by System-Glitch** [comment]
v5 is not out yet and there is still a lot of work to do.
