### ISSUE TITLE
Clickhouse database dialect

### ISSUE THREAD

**Issue by System-Glitch** [go-goyave/goyave#195]
Create a [new database dialect](https://goyave.dev/basics/database.html#drivers) to support Gorm's official [Clickhouse driver](https://github.com/go-gorm/clickhouse).

**Comment by AidanKenney** [comment]
Hey @System-Glitch, I'd be happy to give this a shot.

**Comment by System-Glitch** [comment]
Hello! I'm glad to hear that! If you need assistance, feel free to ask here or on our discord server.
