### ISSUE TITLE
Validation: use default language if not provided

### ISSUE THREAD

**Issue by System-Glitch** [go-goyave/goyave#213]
## Proposal

When using validation manually, not providing the `Language` field in the `validation.Options` will trigger a `panic: runtime error: invalid memory address or nil pointer dereference`.

We should load the built-in default language (`en-US`) if the option is omitted. Or we could use an empty language that would return only the name of the entry.

### Possible drawbacks

Loading the default language for every validation can reduce performance a bit. This would still be very much recommended to use the option. This would need to be properly documented.

**Comment by BowlOfSoup** [comment]
As you suggested in the discusion on Discord, we could also detect _if_ a language is been given. If not, we just return the entry name/input-as-is without translation, thus not using a language lookup in `validator.go:processAddedErrors()`.
