### ISSUE TITLE
Not found error skipped in JWT Controller

### ISSUE THREAD

**Issue by akhedrane** [go-goyave/goyave#221]
Hello, 
Not found error skipped in JWT Controller that caused reflection error on line 123
https://github.com/go-goyave/goyave/blob/3e4f090a2c5ac7c02cb17cf47a64d6958f9f5ffa/auth/jwt_controller.go#L123

**Comment by System-Glitch** [comment]
Hello. Thank you for your report. Can you include a stack trace please?

**Comment by akhedrane** [comment]
the stack trace:


> reflect: call of reflect.Value.FieldByName on zero Value
trace: 
reflect.flag.mustBe
        /Go/src/reflect/value.go:233
reflect.Value.FieldByName
        /Go/src/reflect/value.go:1361
goyave.dev/goyave/v5/auth.(*JWTController[...]).Login
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/auth/jwt_controller.go:123
goyave.dev/goyave/v5.(*validateRequestMiddleware).Handle.func1
       /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:202
goyave.dev/goyave/v5/middleware/parse.(*Middleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware/parse/parse.go:55
goyave.dev/goyave/v5/middleware/parse.(*Middleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware/parse/parse.go:97
goyave.dev/goyave/v5/auth.(*Handler[...]).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/auth/authenticator.go:70
goyave.dev/goyave/v5/log.(*AccessMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/log/log.go:100
goyave.dev/goyave/v5.(*corsMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:237
goyave.dev/goyave/v5.(*languageMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:118
goyave.dev/goyave/v5.(*recoveryMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:90
goyave.dev/goyave/v5.(*Router).requestHandler
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/router.go:511
goyave.dev/goyave/v5.(*Router).ServeHTTP
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/router.go:284
net/http.serverHandler.ServeHTTP
        /Go/src/net/http/server.go:3142
net/http.(*conn).serve
        /Go/src/net/http/server.go:2044

**Comment by akhedrane** [comment]
``` 
ERROR  2024/08/08 10:03:05.14237 (/go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:84)

reflect: call of reflect.Value.FieldByName on zero Value
trace: 
reflect.flag.mustBe
       /Go/src/reflect/value.go:233
reflect.Value.FieldByName
        /Go/src/reflect/value.go:1361
goyave.dev/goyave/v5/auth.(*JWTController[...]).Login
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/auth/jwt_controller.go:123
goyave.dev/goyave/v5.(*validateRequestMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:202
goyave.dev/goyave/v5/middleware/parse.(*Middleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware/parse/parse.go:55
goyave.dev/goyave/v5/middleware/parse.(*Middleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware/parse/parse.go:97
goyave.dev/goyave/v5/auth.(*Handler[...]).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/auth/authenticator.go:70
goyave.dev/goyave/v5/log.(*AccessMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/log/log.go:100
goyave.dev/goyave/v5.(*corsMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:237
goyave.dev/goyave/v5.(*languageMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:118
goyave.dev/goyave/v5.(*recoveryMiddleware).Handle.func1
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/middleware.go:90
goyave.dev/goyave/v5.(*Router).requestHandler
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/router.go:511
goyave.dev/goyave/v5.(*Router).ServeHTTP
        /go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/router.go:284
net/http.serverHandler.ServeHTTP
        /src/net/http/server.go:3142
net/http.(*conn).serve
        /src/net/http/server.go:2044

 INFO  2024/08/08 10:03:05.14237 (/go/pkg/mod/goyave.dev/goyave/v5@v5.2.0/log/log.go:79)
127.0.0.1 - - [08/Aug/2024:10:03:05 +0100] "POST "/login" HTTP/1.1" 500 69 "" "PostmanRuntime/7.41.0"
```

**Comment by akhedrane** [comment]
This error occurred after trying to login with non-exist username in [goyave-blog-example](https://github.com/go-goyave/goyave-blog-example)
