### ISSUE TITLE
Implement the ability to cache data in Redis

### ISSUE THREAD

**Issue by zKoz210** [go-goyave/goyave#222]
## Proposal

**Discussion:** 

Hello. This is the first time I’ve seen a GoLang framework that really covers the basic functionality. I would like to see an implementation of data caching in Redis.

1. Connection to Redis / configuration file
2. An example of connecting and implementing storage for a high-load route. Which saves the result for a certain time and if it has passed, it recaches it.

Thank you for your work!

**Comment by System-Glitch** [comment]
Hello, thank you for your suggestion.

What kind of data would you like to cache into redis? Could you please provide an example use-case as well as a rough cache criteria (when to call the cache, when to return a brand new response, etc)

This could be interesting but there are a ton of special cases to cover.

**Comment by zKoz210** [comment]
I use fairly simple caching. There is a route /cities that gives a list of cities (in my case there are about 1000 of them).

1. GET request to /cities
2. We check whether CitiesStorage has a list of cities by country_id; if there is, then we return it.

1. GET request to /cities
2. Check if CitiesStorage has a list of cities; there is no data in the storage.
3. I make a query in the PostgreSQL database with a specific filter and parameter (for example, county_id).
4. We get the result and save it in Redis for 24 hours.

How does data invalidation occur?

1. I can change the data through the admin panel and delete the cached dto array.
2. By time. The first user request triggers data caching and will take a little longer than subsequent ones. Here you may need to take into account that there can be a lot of requests at a time and so that there are not many saves in Radish, take this into account.

You can come up with something similar with posts for a blog or news site, I think it will look almost the same there. I would like to take into account that I want to save both the data array in batches and the ability to cache a more complete version of the city data under a specific ID if I go, for example, to its detailed page.

Sorry for my English, it's not my native language. If something is unclear, I can try to describe it differently. Thank you!

**Comment by System-Glitch** [comment]
I don't think we need to create a new module in the framework for this. This can (and should) be done at the repository level.

I think that there are too many possible cases and different configurations depending on the content and the policy. It would probably be very hard to implement a one-fits-all solution as part of the framework.

**Comment by zKoz210** [comment]
Here, we rather need an example similar to gorm, so that it can connect from under the hood. The rest is up to the developer
