### ISSUE TITLE
error when filter with clickhouse as database

### ISSUE THREAD

**Issue by manh7890** [go-goyave/goyave#227]
## Bug report

**Version:** [v5.2.1]  
**Environment:** [go1.22.0 linux/amd64]  
**Reproduces:** [sometimes]  

Hi i am using blog example as a base to learn goyave and i currently add goyave filter to my project but is seem dont work for me .I currently using clickhouse as database and every time i run query create by filter is tell me invalid query
![image](https://github.com/user-attachments/assets/5c5f53d4-6205-4cf6-822e-ca8a6e38c00a)
i try to run that query in clickhouse client and even write a simple code to test and is work ok 
![image](https://github.com/user-attachments/assets/74f9ca77-6d7b-40b7-b412-1a6944fb0dc3)
my double check my config with add some data to table with db.Create in your goyave database file is still work and insert data ok so i dont think that my config is wrong but still i may miss some config so here is my config file 
{
    "app": {
        "name": "goyave-blog-example",
        "environment": "localhost",
        "debug": true,
        "defaultLanguage": "en-US"
    },
    "server": {
        "host": "127.0.0.1",
        "domain": "",
        "port": 8080,
        "writeTimeout": 10,
        "readTimeout": 10,
        "readHeaderTimeout": 10,
        "idleTimeout": 20,
        "websocketCloseTimeout": 10,
        "maxUploadSize": 10.0,
        "proxy": {
            "protocol": "http",
            "host": "",
            "port": 80,
            "base": ""
        }
    },
    "database": {
        "connection": "clickhouse",
        "host": "127.0.0.1",
        "port": 9000,
        "name": "manh_test",
        "username": "default",
        "password": "1",
        "options": "dial_timeout=10s",
        "maxOpenConnections": 20,
        "maxIdleConnections": 20,
        "maxLifetime": 300,
        "defaultReadQueryTimeout": 20000,
        "defaultWriteQueryTimeout": 40000,
        "config": {
            "skipDefaultTransaction": false,
            "dryRun": false,
            "prepareStmt": true,
            "disableNestedTransaction": false,
            "allowGlobalUpdate": false,
            "disableAutomaticPing": false,
            "disableForeignKeyConstraintWhenMigrating": false
        }
    },
    "auth": {
        "jwt": {
            "secret": "jwt-secret",
            "expiry": 3000
        }
    }
}
if you know some thing is wrong please tell me

**Comment by manh7890** [comment]
i try again today is seem that all the Select is not working i try db.First but is not working but db create is insert ok i dont know what wrong. I try to run the select query in clickhouse client is still run well

**Comment by System-Glitch** [comment]
It looks like there are many unsupported things in the clickhouse driver. I really struggled (and didn't succeed) to set up the blog example project to be working with clickhouse. The seeds do not work neither (they are inserts though...) because of another error: `clickhouse [AppendRow]: converting clause.Expr to UInt64 is unsupported`.

I can't make any select query work neither. Even the simplest "SELECT *" query returns the "invalid query" error:
```go
var users []*model.User
server.DB().Table("users").Select("*").Find(&users) // SELECT * FROM `users`
```

I tried different configurations and managed to make these work by setting `database.config.prepareStmt` to `false`.
