### ISSUE TITLE
add header failed after response in middle

### ISSUE THREAD

**Issue by fnoopv** [go-goyave/goyave#231]
## Bug report

**Version:** [5.4.0]  
**Environment:** [1.23.2]  
**Reproduces:** [always]  

```go
package middleware

import (
	"goyave.dev/goyave/v5"
)

type Session struct {
	goyave.Component
}

func (se *Session) Handle(next goyave.Handler) goyave.Handler {
	return func(response *goyave.Response, request *goyave.Request) {

		next(response, request)

		addHeaderIfMissing(response, "Cache-Control", `no-cache="Set-Cookie"`)
		addHeaderIfMissing(response, "Vary", "Cookie")
	}
}

func addHeaderIfMissing(w *goyave.Response, key, value string) {
	for _, h := range w.Header()[key] {
		if h == value {
			return
		}
	}
	w.Header().Add(key, value)
}
```

The final response does not contain the `Vary` and `Cache-Control` headers

**Comment by System-Glitch** [comment]
This is the expected behavior. Changing the headers after something has been written to the body isn't possible. The [docs](https://goyave.dev/getting-started/architecture.html#pre-write) states:

> There is a `PreWrite()` hook allowing to alter the response headers or status before the response HTTP headers are written. Once written, they are locked until the end of the request's life: only the body can be written to. This allows the framework to only send the status header when something is being written to the body or when the request is finalized.
>
> For example, the gzip chained writer would ensure a Content-Type header deduced from the uncompressed data is set before the body is actually written.

**Comment by fnoopv** [comment]
copy
