### ISSUE TITLE
Route parameter converter

### ISSUE THREAD

**Issue by System-Glitch** [go-goyave/goyave#93]
## Proposal

Route parameter converters are functions converting route parameters into another type of data, typically models. The main use-case would be to create a built-in url converter for models removing parameter int conversion and SQL query from the controller.

For example, for the following route definition:
```
GET /user/{User}
```
The route parameter converter would take the "User" route parameter and search for the "User" registered model based on its primary key (defined by the gorm tag) in database. If no record is found, then the route will not match and a 404 error will be returned.

This feature could be implemented in a middleware or in the core of the router. However, for performance reasons, a middleware called after the route matched with the current simple matching process would be preferred. That would avoid a lot of unnecessary SQL queries.

Developers using the framework should be able to implement route parameter converters. How to define which converter to use when defining a route is a question that remains open.

### Possible drawbacks

It may be difficult to handle multi-parameter routes and especially relations between models. For example, the following route is retrieving a forum post from the author "User":
```
GET /user/{User}/post/{Post}
```

How could we check and guarantee that the Post is related to User? Should we use the gorm field tags? What if there are multiple foreign keys to the same table?

An expensive work of reflection may be needed for this kind of use-case.

## Additional information

This issue is a feature proposal and is meant to be discussed.
It is also a good candidate if you want to contribute to the project.

**Comment by MShoaei** [comment]
How exactly do you intend to send a `struct` in URI? Would you please send and example input?

**Comment by System-Glitch** [comment]
@MShoaei 
Let's say we have a `Product` struct model. The idea behind this would be to declare a route like this:
```go
router.Get("/product/{Product}", product.Show, nil)
```

A request to show the Product with the ID (primary key) "4" would be:
```
GET /product/4
```

The framework would do something like this:
```go
product := model.Product{}
database.GetConnection().First(&product, request.Params["Product"])

// Override the raw parameter with the struct
request.Params["Product"] = product
```

This is just a draft, and that would require the `request.Params` map to be changed to a `map[string]interface{}`, which is not ideal, but hopefully you get the idea.

**Comment by System-Glitch** [comment]
I prefer to ditch this idea. It is already easy enough to retrieve the model.
